### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by jacekpaszkowski** [syssi/nextbike#1]
Hi,

i get those errors in logs each 5 minutes

```
2020-12-08 23:28:53 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nextbike/sensor.py", line 175, in async_refresh
    self.places = city[ATTR_COUNTRIES][0][ATTR_CITIES][0][ATTR_PLACES]
IndexError: list index out of range
```

my configuration is:

```yaml
  - platform: nextbike
    name: Near bikes 1
    city_id: 210
    latitude: 52.3195433
    longitude: 20.9972433
    radius: 1000

  - platform: nextbike
    name: Near bikes 2
    latitude: 52.2767498
    longitude: 20.9672354
    city_id: 210
    radius: 1500
```

**Comment by syssi** [comment]
Please try again and re-open the issue if the issue isn't solved.

**Comment by paszczaq** [comment]
Same error came back on my instance

```
Logger: homeassistant
Source: custom_components/nextbike/sensor.py:177
Integration: nextbike ([documentation](https://github.com/syssi/nextbike), [issues](https://github.com/syssi/nextbike/issues))
First occurred: 17:50:04 (67 occurrences)
Last logged: 23:20:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nextbike/sensor.py", line 177, in async_refresh
    self.places = city[ATTR_COUNTRIES][0][ATTR_CITIES][0][ATTR_PLACES]
                  ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
