### ISSUE TITLE
Integration broken on HAss 2023.03

### ISSUE THREAD

**Issue by C0ntroller** [syssi/nextbike#5]
Since updating the integration wont start anymore. 

Details from logging tab:

````
Logger: homeassistant.components.sensor
Source: custom_components/nextbike/sensor.py:141
Integration: Sensor (documentation, issues)
First occurred: 3. März 2023 um 19:37:09 (1 occurrences)
Last logged: 3. März 2023 um 19:37:09

Error while setting up nextbike platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/nextbike/sensor.py", line 141, in async_setup_platform
    if not hass.config.units.is_metric:
AttributeError: 'UnitSystem' object has no attribute 'is_metric'
```

**Comment by syssi** [comment]
I will have a look.

**Comment by syssi** [comment]
I've pushed a fix and prepared a new release. Please update to version 1.1.0.
